// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structs.proto

package vectorcopy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VectorMap struct {
	Vector               map[uint32]uint32 `protobuf:"bytes,1,rep,name=Vector,proto3" json:"Vector,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VectorMap) Reset()         { *m = VectorMap{} }
func (m *VectorMap) String() string { return proto.CompactTextString(m) }
func (*VectorMap) ProtoMessage()    {}
func (*VectorMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_e774e8f5f348d14d, []int{0}
}

func (m *VectorMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorMap.Unmarshal(m, b)
}
func (m *VectorMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorMap.Marshal(b, m, deterministic)
}
func (m *VectorMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorMap.Merge(m, src)
}
func (m *VectorMap) XXX_Size() int {
	return xxx_messageInfo_VectorMap.Size(m)
}
func (m *VectorMap) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorMap.DiscardUnknown(m)
}

var xxx_messageInfo_VectorMap proto.InternalMessageInfo

func (m *VectorMap) GetVector() map[uint32]uint32 {
	if m != nil {
		return m.Vector
	}
	return nil
}

type VectorArray struct {
	Vector               []uint32 `protobuf:"varint,1,rep,packed,name=Vector,proto3" json:"Vector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorArray) Reset()         { *m = VectorArray{} }
func (m *VectorArray) String() string { return proto.CompactTextString(m) }
func (*VectorArray) ProtoMessage()    {}
func (*VectorArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_e774e8f5f348d14d, []int{1}
}

func (m *VectorArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorArray.Unmarshal(m, b)
}
func (m *VectorArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorArray.Marshal(b, m, deterministic)
}
func (m *VectorArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorArray.Merge(m, src)
}
func (m *VectorArray) XXX_Size() int {
	return xxx_messageInfo_VectorArray.Size(m)
}
func (m *VectorArray) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorArray.DiscardUnknown(m)
}

var xxx_messageInfo_VectorArray proto.InternalMessageInfo

func (m *VectorArray) GetVector() []uint32 {
	if m != nil {
		return m.Vector
	}
	return nil
}

type Elem struct {
	Index                uint32   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Value                uint32   `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Elem) Reset()         { *m = Elem{} }
func (m *Elem) String() string { return proto.CompactTextString(m) }
func (*Elem) ProtoMessage()    {}
func (*Elem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e774e8f5f348d14d, []int{2}
}

func (m *Elem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Elem.Unmarshal(m, b)
}
func (m *Elem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Elem.Marshal(b, m, deterministic)
}
func (m *Elem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Elem.Merge(m, src)
}
func (m *Elem) XXX_Size() int {
	return xxx_messageInfo_Elem.Size(m)
}
func (m *Elem) XXX_DiscardUnknown() {
	xxx_messageInfo_Elem.DiscardUnknown(m)
}

var xxx_messageInfo_Elem proto.InternalMessageInfo

func (m *Elem) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Elem) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type VectorList struct {
	List                 []*Elem  `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorList) Reset()         { *m = VectorList{} }
func (m *VectorList) String() string { return proto.CompactTextString(m) }
func (*VectorList) ProtoMessage()    {}
func (*VectorList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e774e8f5f348d14d, []int{3}
}

func (m *VectorList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorList.Unmarshal(m, b)
}
func (m *VectorList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorList.Marshal(b, m, deterministic)
}
func (m *VectorList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorList.Merge(m, src)
}
func (m *VectorList) XXX_Size() int {
	return xxx_messageInfo_VectorList.Size(m)
}
func (m *VectorList) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorList.DiscardUnknown(m)
}

var xxx_messageInfo_VectorList proto.InternalMessageInfo

func (m *VectorList) GetList() []*Elem {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*VectorMap)(nil), "vectorcopy.VectorMap")
	proto.RegisterMapType((map[uint32]uint32)(nil), "vectorcopy.VectorMap.VectorEntry")
	proto.RegisterType((*VectorArray)(nil), "vectorcopy.VectorArray")
	proto.RegisterType((*Elem)(nil), "vectorcopy.Elem")
	proto.RegisterType((*VectorList)(nil), "vectorcopy.VectorList")
}

func init() { proto.RegisterFile("structs.proto", fileDescriptor_e774e8f5f348d14d) }

var fileDescriptor_e774e8f5f348d14d = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x2a,
	0x4d, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0x4b, 0x4d, 0x2e, 0xc9,
	0x2f, 0x4a, 0xce, 0x2f, 0xa8, 0x54, 0x6a, 0x64, 0xe4, 0xe2, 0x0c, 0x03, 0x73, 0x7d, 0x13, 0x0b,
	0x84, 0x2c, 0xb9, 0xd8, 0x20, 0x1c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x45, 0x3d, 0x84,
	0x52, 0x3d, 0xb8, 0x32, 0x28, 0xcb, 0x35, 0xaf, 0xa4, 0xa8, 0x32, 0x08, 0xaa, 0x41, 0xca, 0x92,
	0x8b, 0x1b, 0x49, 0x58, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x37, 0x08, 0xc4, 0x14, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b,
	0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x4a, 0xaa, 0x30, 0xad, 0x8e, 0x45, 0x45, 0x89, 0x95, 0x42,
	0x62, 0x28, 0x8e, 0xe0, 0x85, 0xd9, 0xa0, 0x64, 0xc4, 0xc5, 0xe2, 0x9a, 0x93, 0x9a, 0x0b, 0x32,
	0xc8, 0x33, 0x2f, 0x25, 0xb5, 0x02, 0x6a, 0x38, 0x84, 0x03, 0x12, 0x0d, 0x43, 0x36, 0x1e, 0xcc,
	0x51, 0x32, 0xe2, 0xe2, 0x82, 0xe8, 0xf6, 0xc9, 0x2c, 0x2e, 0x11, 0x52, 0xe1, 0x62, 0x01, 0xd1,
	0x50, 0xcf, 0x09, 0x20, 0x7b, 0x0e, 0x64, 0x72, 0x10, 0x58, 0x36, 0x89, 0x0d, 0x1c, 0x4a, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x7b, 0x12, 0x57, 0x36, 0x01, 0x00, 0x00,
}
